#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Dec 01 16:30:31 CET 2021
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto f1c891a660484d80b33b0b2cefe3348a --incr --debug typical --relax --mt 8 --include "../../../../project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_ARCACHE_0/sysc" --include "../../../../project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_ARCACHE_0/sim" --include "../../../../project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_ARUSER_0/sysc" --include "../../../../project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_ARUSER_0/sim" --include "../../../../project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_xlconstant_0_0/sysc" --include "../../../../project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_xlconstant_0_0/sim" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_rsa_wrapper_behav xil_defaultlib.tb_rsa_wrapper xil_defaultlib.glbl -log elaborate.log
