# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# TCL: /home/yz/Projects/Digital_Platform_Design/design_package/hw_project/tcl/constraints.tcl

# IP: ip/adder_DSP/adder_DSP.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_DSP || ORIG_REF_NAME==adder_DSP} -quiet] -quiet
