#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 14 14:46:54 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_montgomery_time_impl -key {Post-Implementation:sim_1:Timing:tb_montgomery} -tclbatch tb_montgomery.tcl -log simulate.log"
xsim tb_montgomery_time_impl -key {Post-Implementation:sim_1:Timing:tb_montgomery} -tclbatch tb_montgomery.tcl -log simulate.log

