webtalk_init -webtalk_dir /home/yz/Projects/Digital_Platform_Design/design_package/hw_project/project_hw/project_hw.sim/sim_1/impl/timing/xsim/xsim.dir/tb_montgomery_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 14 14:51:59 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0d62e389-857a-4cc3-bfab-95e4e48dd97e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "95908b24bbff47ac8011bc4bd9809fbc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3943.699 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30815 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "152948_KB" -context "xsim\\usage"
webtalk_transmit -clientid 15894477 -regid "" -xml /home/yz/Projects/Digital_Platform_Design/design_package/hw_project/project_hw/project_hw.sim/sim_1/impl/timing/xsim/xsim.dir/tb_montgomery_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/yz/Projects/Digital_Platform_Design/design_package/hw_project/project_hw/project_hw.sim/sim_1/impl/timing/xsim/xsim.dir/tb_montgomery_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/yz/Projects/Digital_Platform_Design/design_package/hw_project/project_hw/project_hw.sim/sim_1/impl/timing/xsim/xsim.dir/tb_montgomery_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
